### ISSUE TITLE
Undefined index: media_url

### ISSUE THREAD

**Issue by geo903** [Dymantic/laravel-instagram-feed#46] opened 2021-11-09 11:24 UTC
Hello!

2 days ago, there was a problem in the logs and in the email notification when the data was updated (I am using version 2.6):

[2021-11-09 11:12:16] local.ERROR: Undefined index: media_url {"exception":"[object] (ErrorException(code: 0): Undefined index: media_url at /srv/www/goldenblues/vendor/dymantic/laravel-instagram-feed/src/MediaParser.php:90)

**Comment by michaeljoyner** [comment] 2021-11-09 14:49
Hi @geo903 thanks for reporting this. Seems like I have the same issue. I'll take a look in the morning to see what the cause is.

**Comment by michaeljoyner** [comment] 2021-11-10 00:06
Oddly, everything seems to be working now, and I haven't made any changes. The error comes from the 'media_url' not being present on the children of an album/carousel, but that should always be given by the API. I'm going to leave this open for now in case this persists for others.

If you have had this issue yourself, please run the `php artisan instagram-feed:refresh` command manually to see if you still get the same error. Thanks.

**Comment by geo903** [comment] 2021-11-12 10:28
yes, a few days no error

**Comment by michaeljoyner** [comment] 2021-11-17 09:56
My apologies @geo903, I forgot to reply. Thanks for getting back on this. I haven't had the error again either, so I'm going to close this for now. Thanks again.

**Closed by michaeljoyner** 2021-11-17 09:56 UTC
